source 'https://github.com/jaccty/MXSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'MXAuthorKit_Example' do
  pod 'MXAuthorKit', :path => '../'

  target 'MXAuthorKit_Tests' do
    inherit! :search_paths

    
  end
end
